<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Security Guards List</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
            margin: 0;
            padding: 0;
        }

        /* Container for the PDF */
        .container {
            padding: 20px;
        }

        /* Logo and header */
        .header {
            text-align: center;
            margin-bottom: 30px;
        }

        .header img {
            width: 100px; /* Adjust the logo size */
            margin-bottom: 10px;
        }

        .header h1 {
            margin: 0;
            font-size: 24px;
            color: #333;
        }

        /* Table styles */
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }

        table, th, td {
            border: 1px solid #ddd;
        }

        th, td {
            padding: 8px;
            text-align: left;
        }

        th {
            background-color: #f4f4f4;
            color: #333;
            font-weight: bold;
        }

        /* Responsive design for smaller screens */
        @media (max-width: 600px) {
            table {
                font-size: 10px;
            }
        }

        /* Footer (if needed) */
        .footer {
            margin-top: 40px;
            text-align: center;
            font-size: 10px;
            color: #999;
        }
    </style>
</head>
<body>

    <div class="container">
        <!-- Header with logo and title -->
        <div class="header">
            <img src="path_to_your_logo.png" alt="Company Logo"> <!-- Replace with the actual path to your logo -->
            <h1>Security Guards List</h1>
        </div>

        <!-- Table containing security guard information -->
        <table>
            <thead>
                <tr>
                    <th>#</th>
                    <th>Surname</th>
                    <th>Firstname</th>
                    <th>Middlename</th>
                    <th>Email</th>
                    <th>Phone Number</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($securityGuards as $key => $securityGuard)
                    <tr>
                        <td>{{ ++$key }}</td>
                        <td>{{ $securityGuard->surname }}</td>
                        <td>{{ $securityGuard->first_name }}</td>
                        <td>{{ $securityGuard->middle_name }}</td>
                        <td>{{ $securityGuard->email }}</td>
                        <td>{{ $securityGuard->phone_number }}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>

        <!-- Optional Footer -->
        <div class="footer">
            <p>Generated by [SKOTE] | {{ \Carbon\Carbon::now()->format('F j, Y') }}</p>
        </div>
    </div>

</body>
</html>
